import { RootProvider } from '@/components/provider/root-provider';
import { cn } from '@/lib/utils';
import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  JetBrains_Mono,
  Noto_Sans,
  Playfair_Display,
} from 'next/font/google';
import './globals.css';

const playfairDisplayHeading = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-heading',
});

const notoSans = Noto_Sans({ subsets: ['latin'], variable: '--font-sans' });

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      suppressHydrationWarning
      lang='en'
      className={cn(
        'h-full',
        'antialiased',
        geistSans.variable,
        geistMono.variable,
        jetbrainsMono.variable,
        'font-sans',
        notoSans.variable,
        playfairDisplayHeading.variable,
      )}
    >
      <body className='min-h-full flex flex-col dark'>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
